ALLOWED_HOSTS:
- '*'
APPEARANCE_MAXIMUM_TITLE_LENGTH: 120
APPEARANCE_MESSAGE_POSITION: top-right
APPEND_SLASH: true
AUTHENTICATION_BACKENDS:
- django.contrib.auth.backends.ModelBackend
AUTHENTICATION_DISABLE_PASSWORD_RESET: false
AUTHENTICATION_LOGIN_METHOD: username
AUTHENTICATION_MAXIMUM_SESSION_LENGTH: 2592000
AUTH_PASSWORD_VALIDATORS:
- NAME: django.contrib.auth.password_validation.UserAttributeSimilarityValidator
- NAME: django.contrib.auth.password_validation.MinimumLengthValidator
- NAME: django.contrib.auth.password_validation.CommonPasswordValidator
- NAME: django.contrib.auth.password_validation.NumericPasswordValidator
AUTOADMIN_EMAIL: autoadmin@example.com
AUTOADMIN_PASSWORD: null
AUTOADMIN_USERNAME: admin
CELERY_BROKER_LOGIN_METHOD: AMQPLAIN
CELERY_BROKER_URL: redis://:mayanredispassword@redis:6379/0
CELERY_BROKER_USE_SSL: null
CELERY_RESULT_BACKEND: redis://:mayanredispassword@redis:6379/1
COMMON_AUTO_LOGGING: true
COMMON_DB_SYNC_TASK_DELAY: 2
COMMON_DISABLED_APPS: []
COMMON_EXTRA_APPS: []
COMMON_HOME_VIEW: common:home
COMMON_PAGINATE_BY: 40
COMMON_PRODUCTION_ERROR_LOGGING: false
COMMON_PRODUCTION_ERROR_LOG_PATH: /var/lib/mayan/error.log
COMMON_PROJECT_TITLE: Mayan EDMS
COMMON_PROJECT_URL: https://www.mayan-edms.com
COMMON_SHARED_STORAGE: django.core.files.storage.FileSystemStorage
COMMON_SHARED_STORAGE_ARGUMENTS:
  location: /var/lib/mayan/shared_files
COMMON_URL_BASE_PATH: ''
CONVERTER_GRAPHICS_BACKEND: mayan.apps.converter.backends.python.Python
CONVERTER_GRAPHICS_BACKEND_ARGUMENTS:
  libreoffice_path: /usr/bin/libreoffice
  pdfinfo_path: /usr/bin/pdfinfo
  pdftoppm_dpi: 300
  pdftoppm_format: jpeg
  pdftoppm_path: /usr/bin/pdftoppm
  pillow_format: JPEG
  pillow_maximum_image_pixels: 89478485
DATABASES:
  default:
    ENGINE: django.db.backends.postgresql
    HOST: postgresql
    NAME: mayan
    PASSWORD: mayandbpass
    USER: mayan
DATA_UPLOAD_MAX_MEMORY_SIZE: 2621440
DEFAULT_FROM_EMAIL: webmaster@localhost
DISALLOWED_USER_AGENTS: []
DOCUMENTS_CACHE_MAXIMUM_SIZE: 524288000
DOCUMENTS_CACHE_STORAGE_BACKEND: django.core.files.storage.FileSystemStorage
DOCUMENTS_CACHE_STORAGE_BACKEND_ARGUMENTS:
  location: /var/lib/mayan/document_cache
DOCUMENTS_DISABLE_BASE_IMAGE_CACHE: false
DOCUMENTS_DISABLE_TRANSFORMED_IMAGE_CACHE: false
DOCUMENTS_DISPLAY_HEIGHT: ''
DOCUMENTS_DISPLAY_WIDTH: '3600'
DOCUMENTS_FAVORITE_COUNT: 400
DOCUMENTS_FIX_ORIENTATION: false
DOCUMENTS_HASH_BLOCK_SIZE: 65535
DOCUMENTS_LANGUAGE: eng
DOCUMENTS_LANGUAGE_CODES:
- ilo
- run
- uig
- hin
- pan
- pnb
- wuu
- msa
- kxd
- ind
- zsm
- jax
- meo
- kvr
- xmm
- min
- mui
- zmi
- max
- mfa
- cjy
- nan
- pus
- pbu
- pbt
- wne
- hsn
- hak
- ful
- fuc
- fuf
- ffm
- fue
- fuh
- fuq
- fuv
- fub
- fui
- nep
- npi
- dty
- sin
- khm
- kxm
- ell
- grc
- cpg
- gmy
- pnt
- tsd
- yej
- nya
- mnp
- dhd
- cdo
- hil
- bcc
- bgn
- bgp
- cmn
- kok
- spa
- eng
- ara
- por
- ben
- rus
- jpn
- deu
- jav
- tel
- vie
- kor
- fra
- mar
- tam
- urd
- tur
- ita
- yue
- tha
- guj
- fas
- pol
- kan
- mal
- sun
- hau
- ory
- mya
- ukr
- bho
- tgl
- yor
- mai
- uzb
- snd
- amh
- ron
- orm
- ibo
- aze
- awa
- gan
- ceb
- nld
- kur
- hbs
- mlg
- skr
- ctg
- zha
- tuk
- asm
- mad
- som
- mwr
- mag
- bgc
- hun
- hne
- dcc
- aka
- kaz
- syl
- zul
- ces
- kin
- hat
- que
- swe
- hmn
- sna
- mos
- xho
- bel
DOCUMENTS_LIST_THUMBNAIL_WIDTH: '50'
DOCUMENTS_PAGE_IMAGE_CACHE_TIME: '31556926'
DOCUMENTS_PREVIEW_HEIGHT: ''
DOCUMENTS_PREVIEW_WIDTH: '800'
DOCUMENTS_PRINT_HEIGHT: ''
DOCUMENTS_PRINT_WIDTH: '3600'
DOCUMENTS_RECENT_ACCESS_COUNT: 400
DOCUMENTS_RECENT_ADDED_COUNT: 400
DOCUMENTS_ROTATION_STEP: 90
DOCUMENTS_STORAGE_BACKEND: django.core.files.storage.FileSystemStorage
DOCUMENTS_STORAGE_BACKEND_ARGUMENTS:
  location: /var/lib/mayan/document_storage
DOCUMENTS_STUB_EXPIRATION_INTERVAL: 86400
DOCUMENTS_THUMBNAIL_HEIGHT: ''
DOCUMENTS_THUMBNAIL_WIDTH: '800'
DOCUMENTS_ZOOM_MAX_LEVEL: 300
DOCUMENTS_ZOOM_MIN_LEVEL: 25
DOCUMENTS_ZOOM_PERCENT_STEP: 25
DOCUMENT_PARSING_AUTO_PARSING: true
DOCUMENT_PARSING_PDFTOTEXT_PATH: /usr/bin/pdftotext
EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
EMAIL_HOST: localhost
EMAIL_HOST_PASSWORD: ''
EMAIL_HOST_USER: ''
EMAIL_PORT: 25
EMAIL_TIMEOUT: null
EMAIL_USE_SSL: false
EMAIL_USE_TLS: false
FILE_METADATA_AUTO_PROCESS: true
FILE_METADATA_DRIVERS_ARGUMENTS:
  exif_driver:
    exiftool_path: /usr/bin/exiftool
FILE_UPLOAD_MAX_MEMORY_SIZE: 2621440
INTERNAL_IPS:
- 127.0.0.1
LANGUAGES:
- - ar
  - Arabic
- - bg
  - Bulgarian
- - bs
  - Bosnian
- - cs
  - Czech
- - da
  - Danish
- - de
  - German
- - el
  - Greek
- - en
  - English
- - es
  - Spanish
- - fa
  - Persian
- - fr
  - French
- - hu
  - Hungarian
- - id
  - Indonesian
- - it
  - Italian
- - lv
  - Latvian
- - nl
  - Dutch
- - pl
  - Polish
- - pt
  - Portuguese
- - pt-br
  - Portuguese (Brazil)
- - ro
  - Romanian
- - ru
  - Russian
- - sl
  - Slovenian
- - tr
  - Turkish
- - vi
  - Vietnamese
- - zh-hans
  - Chinese (Simplified)
LANGUAGE_CODE: en-us
LOCK_MANAGER_BACKEND: mayan.apps.lock_manager.backends.file_lock.FileLock
LOCK_MANAGER_BACKEND_ARGUMENTS: {}
LOCK_MANAGER_DEFAULT_LOCK_TIMEOUT: 30
LOGIN_REDIRECT_URL: common:home
LOGIN_URL: authentication:login_view
LOGOUT_REDIRECT_URL: authentication:login_view
MAILER_DOCUMENT_BODY_TEMPLATE: "Attached to this email is the document: {{ document\
  \ }}\n\n --------\n This email has been sent from %(project_title)s (%(project_website)s)"
MAILER_DOCUMENT_SUBJECT_TEMPLATE: 'Document: {{ document }}'
MAILER_LINK_BODY_TEMPLATE: "To access this document click on the following link: {{\
  \ link }}\n\n--------\n This email has been sent from %(project_title)s (%(project_website)s)"
MAILER_LINK_SUBJECT_TEMPLATE: 'Link for document: {{ document }}'
MAYAN_CELERY_CLASS: celery.Celery
METADATA_AVAILABLE_PARSERS:
- mayan.apps.metadata.parsers.DateAndTimeParser
- mayan.apps.metadata.parsers.DateParser
- mayan.apps.metadata.parsers.TimeParser
METADATA_AVAILABLE_VALIDATORS:
- mayan.apps.metadata.validators.DateAndTimeValidator
- mayan.apps.metadata.validators.DateValidator
- mayan.apps.metadata.validators.TimeValidator
MIRRORING_DOCUMENT_CACHE_LOOKUP_TIMEOUT: 10
MIRRORING_NODE_CACHE_LOOKUP_TIMEOUT: 10
OCR_AUTO_OCR: true
OCR_BACKEND: mayan.apps.ocr.backends.tesseract.Tesseract
OCR_BACKEND_ARGUMENTS: {}
REST_API_DISABLE_LINKS: false
SEARCH_BACKEND: mayan.apps.dynamic_search.backends.django.DjangoSearchBackend
SEARCH_BACKEND_ARGUMENTS: {}
SEARCH_DISABLE_SIMPLE_SEARCH: false
SECURE_PROXY_SSL_HEADER: null
SESSION_COOKIE_NAME: sessionid
SESSION_ENGINE: django.contrib.sessions.backends.db
SIGNATURES_BACKEND: mayan.apps.django_gpg.backends.python_gnupg.PythonGNUPGBackend
SIGNATURES_BACKEND_ARGUMENTS:
  gpg_path: /usr/bin/gpg1
SIGNATURES_KEYSERVER: pool.sks-keyservers.net
SIGNATURES_STORAGE_BACKEND: django.core.files.storage.FileSystemStorage
SIGNATURES_STORAGE_BACKEND_ARGUMENTS:
  location: /var/lib/mayan/document_signatures
SMART_SETTINGS_NAMESPACES:
  appearance:
    version: '0001'
  authentication:
    version: '0001'
  autoadmin:
    version: '0001'
  celery:
    version: '0001'
  common:
    version: '0002'
  converter:
    version: '0002'
  django:
    version: '0001'
  django_gpg:
    version: '0001'
  document_parsing:
    version: '0001'
  document_states:
    version: '0001'
  documents:
    version: '0002'
  file_metadata:
    version: '0002'
  lock_manager:
    version: '0001'
  mailer:
    version: '0001'
  mayan:
    version: '0001'
  metadata:
    version: '0001'
  mirroring:
    version: '0001'
  ocr:
    version: '0002'
  rest_api:
    version: '0001'
  search:
    version: '0001'
  signatures:
    version: '0002'
  sources:
    version: '0002'
  storage:
    version: '0001'
SOURCES_SCANIMAGE_PATH: /usr/bin/scanimage
SOURCES_STAGING_FILE_CACHE_STORAGE_BACKEND: django.core.files.storage.FileSystemStorage
SOURCES_STAGING_FILE_CACHE_STORAGE_BACKEND_ARGUMENTS:
  location: /var/lib/mayan/staging_file_cache
STATICFILES_STORAGE: whitenoise.storage.CompressedManifestStaticFilesStorage
STATIC_URL: /static/
STORAGE_TEMPORARY_DIRECTORY: /tmp
TIME_ZONE: UTC
USE_X_FORWARDED_HOST: false
USE_X_FORWARDED_PORT: false
WORKFLOWS_GRAPHVIZ_DOT_PATH: /usr/bin/dot
WORKFLOWS_IMAGE_CACHE_MAXIMUM_SIZE: 52428800
WORKFLOWS_IMAGE_CACHE_STORAGE_BACKEND: django.core.files.storage.FileSystemStorage
WORKFLOWS_IMAGE_CACHE_STORAGE_BACKEND_ARGUMENTS:
  location: /var/lib/mayan/workflows
WORKFLOWS_IMAGE_CACHE_TIME: '31556926'
WSGI_APPLICATION: mayan.wsgi.application
